name: Terraform Apply (main)
on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-apply.yml'

permissions: { id-token: write, contents: read }
concurrency:
  group: tf-apply-${{ github.ref }}
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: portfolio-env  # configure required reviewers no GitHub
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.8.5 }
      - name: Init+Apply (state local por enquanto)
        working-directory: infra/envs/dev
        run: |
          terraform init -backend=false
          terraform apply -auto-approve
